# Generated by Django 3.2 on 2023-08-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kyc_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='kyc_submitted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
