# Generated by Django 3.2 on 2023-08-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230818_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='re_by',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
