# Generated by Django 3.2 on 2023-08-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_re_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='recommend_by',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
