# Generated by Django 3.2 on 2023-08-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20230820_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='account',
            name='recommend_by',
        ),
    ]
