# Generated by Django 3.2 on 2023-08-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_referral_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True, verbose_name='Transaction ID'),
        ),
    ]
