# Generated by Django 3.2 on 2023-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deposits',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='withdrawals',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
