# Generated by Django 3.2 on 2023-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20230826_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(max_length=4, null=True, unique=True, verbose_name='PIN CODE'),
        ),
    ]
