# Generated by Django 3.2 on 2023-08-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_account_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(max_length=4, null=True, unique=True, verbose_name='PIN CODE'),
        ),
    ]
