# Generated by Django 3.2 on 2023-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20230831_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='loan_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
