# Generated by Django 3.2 on 2023-09-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_account_loan_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_fulfilled',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_request',
        ),
    ]
