# Generated by Django 3.2 on 2023-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20230908_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user.png', upload_to='userprofile/%Y%m%d/'),
        ),
    ]
