# Generated by Django 3.2 on 2023-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_chatmessages_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='chats/%Y%m%d/'),
        ),
    ]
