# Generated by Django 3.2 on 2023-10-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_chatmessages_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
