# Generated by Django 3.2 on 2023-10-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_account_is_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessages',
            old_name='user_from',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chatmessages',
            old_name='user_to',
            new_name='sender',
        ),
    ]
