# Generated by Django 3.2 on 2023-10-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20231005_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
