# Generated by Django 3.2 on 2023-10-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_chatmessages_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='image',
        ),
    ]
